[package]
name = "fplus"
version = "0.1.0-2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "fplus"
path = "main.rs"
